name: iblesoy
url : https://iblesoy.github.io/
baseurl: https://iblesoy.github.io/
description: 
lang: ko
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
permalink: /:categories/:title/
sass:
 style: compressed
